### ISSUE TITLE
Kubemark tests with ignite-etcd

### ISSUE THREAD

**Issue by kukushal** [gridgain-solutions/ignite-in-k8s#14]
1. Run Kubemark tests with ignite-etcd
2. Generate test report
3. Share and review the test report with the team

**Comment by vinaykul** [comment]
There's a good overview of kubemark at https://stupefied-goodall-e282f7.netlify.app/contributors/devel/kubemark-guide/

We use GCE to run kubemark performance tests, so this would need a GCE account. There is a way to run it locally as well, but I have not tried it.

Please see the document https://github.com/sonyafenge/arktos-tool/blob/master/perftools/Howtorunperf-tests.md . Please look through the steps to see how it relates to the above overview document.

When bringing up the cluster, the kube-up script sets up the master VM and runs a configure script that starts etcd and runs etcd in a pod (etcd.manifest tells kubelet where to get the container image for etcd and how to start it). And I don't know if etcd-events.manifest is applicable to ignite. Is it?

Please review: 
```
gci/configure-helper-common.sh:function prepare-etcd-manifest {
```
The key thing to do here is to replace etcd with ignite in a way not very different from what we did with local-up-cluster, but it may be a bit more work. Overall though, I think it would be sufficient to replace this function with something like prepare-ignite-manifest, but I may be missing something. 

From the above how-to-run-perf doc (which is specific to our project), I would change the env variables in step 1 as illustrated below (you can choose your own zones, prefixes, net-names):
```
export MASTER_ROOT_DISK_SIZE=100GB MASTER_DISK_SIZE=120GB KUBE_GCE_ZONE=us-west2-b MASTER_SIZE=n1-highmem-32 NODE_SIZE=n1-highmem-8 NUM_NODES=2 NODE_DISK_SIZE=200GB KUBE_GCE_NETWORK=kubemark-500 GOPATH=$HOME/go KUBE_GCE_ENABLE_IP_ALIASES=true KUBE_GCE_PRIVATE_CLUSTER=true CREATE_CUSTOM_NETWORK=true KUBE_GCE_INSTANCE_PREFIX=kubemark-500 KUBEMARK_NUM_NODES=100
```

For starters, just to try things out, an admin cluster with 2 VM nodes (NUM_NODES=2) and 100 virtual nodes is sufficient. You can skip step 2 in above document. 

The k8s perf tests come from repo https://github.com/kubernetes/perf-tests

In my experience, it is best to setup the k8s repo and perf-tests repo under standard go paths for it to work without extra efforts. i.e.
```
~/go/src/k8s.io/kubernetes/
~/go/src/k8s.io/perf-tests/
```

We usually run the load and density perf tests (they can be run separately). To run the perf-tests:
```
cd perf-tests/clusterloader2/
nohup ./run-e2e.sh --nodes=$KUBEMARK_NUM_NODES --provider=kubemark --kubeconfig=$HOME/go/src/k8s.io/kubernetes/test/kubemark/resources/kubeconfig.kubemark --report-dir=$HOME/logs/perf-test/ --testconfig=testing/load/config.yaml --testconfig=testing/density/config.yaml
```
