### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by kukushal** [gridgain-solutions/ignite-in-k8s#9]
Right now version is hard-coded to 1.

Implement versioning using a distributed counter with a backlog cache.

**Comment by deepak-vij** [comment]
Just a curiosity, I thought as part of initial sprint we decided to go with simple global in-memory counter. Just curious about 5 points assigned to this task. We can discuss this more during our regular meeting. I think we all agree that our key goal for Sprint-0 should be that we are able to run unit tests & integration tests by the end of current ongoing sprint-0. That will tell us what are all the gaps, what works and what does not. Accordingly, we can work on these tasks as part of subsequent sprints. Thanks.
